---
# tasks file for selinux
- name: install required packages
  package:
    name: "{{ selinux_requirements }}"
    state: present
  register: selinux_install_required_packages
  until: selinux_install_required_packages is succeeded
  retries: 3

- name: manage selinux
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy }}"
  when:
    - ansible_selinux.status is defined
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "container"
  register: selinux_manage_selinux

- name: restore selinux contexts
  shell: |
    restorecon="$( find /sbin /usr/sbin -iname restorecon )"
    $restorecon -R /usr /etc /var /dev /sys /bin /sbin
  when:
    - selinux_manage_selinux.changed

- name: reboot for selinux
  include_role:
    name: robertdebock.reboot
  when:
    - selinux_manage_selinux.changed
  tags:
    - skip_ansible_lint
